import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, test } from 'node:test';

/**
 * A client who comes back — gap G-016, decision ADM-05.
 *
 * *"One lead per person, forever. A returning client gets a new deal on their
 * existing lead, so their whole history stays in one place."*
 *
 * Two thirds of that already worked and were measured before anything was
 * written: the same phone resolves to the same lead, and a won deal does not
 * block the next one. The third was missing entirely — nothing marked the
 * return, so a client saying "I want a second app" landed in the transcript of
 * a lead nobody was working, with no activity, no event and no change anywhere
 * a person looks.
 *
 * The behaviour is proved against a real Postgres by
 * `scripts/verify-returning-client.mjs` — 16 checks, six of which fail with the
 * trigger removed. What is here is the rules read out of the migration, and
 * above all the three things it must NOT do.
 */

const migration = readFileSync(
  fileURLToPath(
    new URL('../supabase/migrations/20260813120025_a_client_who_comes_back.sql', import.meta.url),
  ),
  'utf8',
);

const ingest = readFileSync(
  fileURLToPath(
    new URL('../supabase/migrations/20260811120002_whatsapp_terminal_lead_extraction.sql', import.meta.url),
  ),
  'utf8',
);

/** Executable SQL: `--` lines and COMMENT ON bodies removed. */
const sql = migration
  .split('\n')
  .filter((l) => !l.trim().startsWith('--'))
  .join('\n')
  .replace(/comment on [\s\S]*?';/gi, '');

describe('A. the checks below are not vacuous', () => {
  test('the stripped SQL is still the migration', () => {
    assert.match(sql, /function crm\.mark_returning_client/);
    assert.match(sql, /function crm\.returning_clients/);
    assert.ok(sql.length > migration.length / 4, 'the strip removed most of the file');
  });
});

describe('B. what marks a return', () => {
  test('only a settled lead — a live one is the ordinary case', () => {
    assert.match(sql, /v_lead\.status not in \('converted', 'disqualified'\)/);
  });

  test('only an inbound message — the agency replying is not a return', () => {
    assert.match(sql, /new\.author_type <> 'client'/);
  });

  test('and only a direct thread, because a group has no lead', () => {
    // G-115: a group conversation carries no lead_id, and a message there is a
    // conversation already in progress rather than somebody coming back.
    assert.match(sql, /v_conv\.lead_id is null or v_conv\.kind <> 'direct'/);
  });

  test('it uses the activity vocabulary that already exists', () => {
    // ADM-10 chose activities as the record of everything the agency does.
    // A new `kind` would need a CHECK change and would say nothing new.
    assert.match(sql, /'message_in'/);
    assert.match(sql, /'returning', true/);
  });
});

describe('C. what it must not do', () => {
  test('it does not move the lead status', () => {
    // `converted` is terminal in LEAD_TRANSITIONS, and ADM-05 gives the
    // returning client a new DEAL rather than a reopened lead. Flipping the
    // status back would rewrite the history of the engagement that closed.
    assert.ok(
      !/update crm\.leads/i.test(sql),
      'the trigger writes to crm.leads — a returning client does not reopen a lead',
    );
  });

  test('it does not invent a follow-up date', () => {
    assert.ok(
      !/next_follow_up_at/.test(sql),
      'when to chase somebody is a rule nobody has written',
    );
  });

  test('it does not open a deal unasked', () => {
    assert.ok(
      !/insert into sales\.opportunities/i.test(sql),
      'a deal with no value, owner or conversation behind it is worse than none',
    );
  });
});

describe('D. why a trigger rather than a change to the ingest', () => {
  test('the ingest function is not regenerated by this migration', () => {
    // Carrying a 200-line function forward to add four lines is exactly the
    // regeneration that silently changed a seq base from -1 to 0 earlier in
    // this same session. The trigger also covers every path into the table,
    // which is the G-093 argument.
    assert.ok(
      !/function crm\.ingest_whatsapp_message/.test(sql),
      'this migration rewrites the ingest, which it does not need to',
    );
  });

  test('and the ingest still stops short of extracting against a settled lead', () => {
    // C6's rule, which this does not change: extraction moves an UNDECIDED
    // lead forward, and a settled deal is not moved forward by proposing
    // requirements at it. The mark replaces the silence, not that rule.
    assert.match(ingest, /if v_lead_status in \('converted', 'disqualified'\) then/);
  });
});

describe('E. reading it back', () => {
  test('the read is side-effect free, so a screen can show it', () => {
    const fn = sql.slice(sql.indexOf('function crm.returning_clients'));
    assert.match(fn.slice(0, 300), /language sql\s+stable/);
  });

  test('it counts only the marks, not every message', () => {
    const fn = sql.slice(sql.indexOf('function crm.returning_clients'));
    assert.match(fn, /metadata->>'returning' = 'true'/);
  });

  test('and skips deleted leads', () => {
    const fn = sql.slice(sql.indexOf('function crm.returning_clients'));
    assert.match(fn, /l\.deleted_at is null/);
  });
});
