/**
 * The words the Phase 8C doors' refusals are shown in. A door answers with a code; this says what it means in plain terms. Anything unlisted is shown as
 * written ("Refused: ..."), never as a success.
 */
const WORDS: Record<string, string> = {
  not_authorized: 'Your role may not do this.',
  no_actor: 'You are not signed in.',
  not_found: 'That record was not found.',
  wrong_state: 'It is not in a state where this can be done.',
  entitlement_required: 'State the included hours or requests: nothing is assumed.',
  name_required: 'A name is required.',
  bad_billing_model: 'Choose monthly, quarterly, annual or prepaid.',
  secret_in_text: 'That text looks like a secret. Record a reference (a ticket or message id), never the secret.',
  author_cannot_publish: 'The author of a version cannot publish it: another Admin must.',
  not_a_draft: 'Only a draft version takes changes; create the next version instead.',
  rate_for_an_unentitled_kind: 'That version does not include that kind of entitlement.',
  already_entered: 'That price line (or overage rate) is already entered on this version.',
  bad_amount: 'The amount must be zero or more, in minor units.',
  bad_currency: 'Use a three-letter currency code.',
  catalog_not_found: 'That catalog version was not found.',
  catalog_not_published: 'Only a published version can be opened as a plan.',
  no_handover: 'There is no delivered handover to maintain yet.',
  project_has_a_live_plan: 'This project already has a plan in progress.',
  plan_exists_for_this_version: 'A plan from this version already exists on this project.',
  evidence_required: 'A reference to the client\'s message or document is required.',
  proposal_not_found: 'That quote was not found.',
  proposal_is_another_clients: 'That quote belongs to another client.',
  quote_not_accepted: 'The quote must be accepted first, through the sales process.',
  quote_not_approved: 'The renewal quote must be approved before it is proposed.',
  already_decided: 'The client\'s decision on this plan is already recorded.',
  reason_required: 'A reason is required.',
  approver_is_the_author: 'You opened, proposed or recorded this: another Admin must decide it.',
  not_accepted: 'The client has not accepted yet.',
  first_cycle_not_billed: 'The first cycle has no invoice linked to it yet.',
  first_cycle_not_paid: 'The first cycle\'s invoice is not paid on verified money and no owner-approved exception stands in for it.',
  bad_kind: 'Choose hours or request.',
  bad_quantity: 'Enter a positive quantity (whole for requests).',
  bad_date: 'Usage cannot be dated in the future.',
  name_a_ticket_or_work_item: 'Name the ticket or work item this usage answers to.',
  plan_not_in_force: 'The plan is not in force: it entitles nothing right now.',
  no_paid_cycle_covers_that_date: 'No paid cycle covers that date.',
  kind_not_in_the_entitlement: 'The plan\'s entitlement does not include that kind.',
  work_item_not_found: 'That work item was not found on this project.',
  ticket_not_found: 'That ticket was not found on this project.',
  warranty_work_is_not_plan_usage: 'Warranty work is the agency\'s cost and does not use the client\'s entitlement.',
  self_reversal: 'Whoever recorded an entry cannot reverse it.',
  already_reversed: 'That entry is already reversed.',
  only_a_consumption_is_reversed: 'Only a consumption entry can be reversed.',
  no_overage: 'There is nothing beyond the entitlement to draft.',
  already_drafted: 'That overage is already drafted.',
  plan_lapsed: 'The plan\'s period has ended: it lapses and needs a new acceptance, it is not revived.',
  bad_period: 'The renewal must run past the day after the current end date.',
  renewal_already_open: 'A renewal is already open on this plan.',
  quote_not_found: 'That quote was not found.',
  renewal_cycle_not_billed: 'The renewal cycle has no invoice linked to it yet.',
  renewal_not_paid: 'The renewal invoice is not paid on verified money and no owner-approved exception stands in for it.',
  plan_not_awaiting_renewal: 'The plan is not waiting on a renewal.',
  bad_reason_code: 'Choose one of the named reasons.',
  cancellation_already_requested: 'A cancellation is already requested for this plan.',
  requester_cannot_confirm: 'Whoever requested the cancellation cannot confirm it.',
  cycle_not_paid: 'The current cycle is not paid on verified money (or excepted) again.',
  stale_commit: 'That evidence is about a different commit than the change now holds.',
  not_a_sensitive_database_change: 'Only a change to the database area takes a data-safety record (the sensitive mark does not decide this).',
  rollback_plan_required: 'A rollback plan is required.',
  backup_evidence_required: 'A backup-confirmed evidence reference is required.',
  self_confirmation: 'The author of the commit cannot confirm their own backup.',
  no_commit_yet: 'No commit has been submitted yet.',
  closed_for_changes: 'This change is already approved, released or cancelled.',
  note_required: 'A note is required.',
  already_acknowledged: 'Already acknowledged.',
  bad_hours: 'Enter a whole number of hours within the allowed range.',
};

export const phaseEightCWords = (outcome: string): string => WORDS[outcome] ?? `Refused: ${outcome.replace(/_/g, ' ')}.`;
