import help from './screens.json' with { type: 'json' };

/**
 * The Help page's data — bucket E, decision E3 (A34).
 *
 * `screens.json` is generated by `scripts/build-help.mjs` from
 * `docs/AGENCYOS_ADMIN_MASTER_SCREEN_INVENTORY.md` and checked in; the guard
 * test fails when it is older than the inventory. This module is pure and
 * dependency-free (no `server-only`, no request context) so the shell's
 * "?" link can resolve the current route in the browser and a test can call
 * the resolver directly.
 */

export type HelpScreen = {
  /** SCR-001 … SCR-071 — the permanent id from the inventory. */
  id: string;
  title: string;
  /** The `### Module` heading the row sits under — the sidebar module. */
  module: string;
  /** The route cell as written, backticks removed. */
  route: string;
  /** Every `/path` in the route cell; `[param]` marks a dynamic segment. */
  routes: string[];
  capability: string;
  reads: string;
  live: string;
  status: string;
};

export type HelpIndex = {
  source: string;
  inventoryHash: string;
  count: number;
  screens: HelpScreen[];
};

export const HELP: HelpIndex = help as HelpIndex;
export const HELP_SCREENS: readonly HelpScreen[] = HELP.screens;

/** The anchor a screen's entry sits under on /help. */
export function helpAnchor(id: string): string {
  return id.toLowerCase();
}

/** `/help#scr-007` — where the "?" on a screen points. */
export function helpHref(screen: HelpScreen | null): string {
  return screen ? `/help#${helpAnchor(screen.id)}` : '/help';
}

function segments(path: string): string[] {
  return path.split('?')[0]!.split('#')[0]!.split('/').filter((s) => s.length > 0);
}

/**
 * How many leading segments of `pathname` a route pattern accounts for, or
 * -1 when it does not match. `[param]` matches any one segment. A pattern
 * matches a deeper path (`/projects/[id]/development` matches
 * `/projects/x/development/tasks/y`) so a sub-page inherits its parent's entry.
 */
function matchDepth(pattern: string, pathname: string): number {
  const want = segments(pattern);
  const have = segments(pathname);
  if (want.length === 0 || want.length > have.length) return -1;
  for (let i = 0; i < want.length; i += 1) {
    const w = want[i]!;
    if (w.startsWith('[') && w.endsWith(']')) continue;
    if (w !== have[i]) return -1;
  }
  return want.length;
}

/**
 * The inventory entry for a pathname: the screen whose route pattern
 * accounts for the most of it; on a tie, the first row in the inventory
 * (SCR-007 Lead 360 before the panels grouped inside it). Null when nothing
 * in the inventory serves the path — the link then points at /help itself.
 */
export function resolveScreen(pathname: string, screens: readonly HelpScreen[] = HELP_SCREENS): HelpScreen | null {
  let best: { screen: HelpScreen; depth: number } | null = null;
  for (const screen of screens) {
    for (const route of screen.routes) {
      const depth = matchDepth(route, pathname);
      if (depth > (best?.depth ?? 0)) best = { screen, depth };
    }
  }
  return best?.screen ?? null;
}

/**
 * Case-insensitive search over id, title, module, route, capability, reads
 * and status. Every word of the query must appear somewhere in the entry.
 */
export function searchScreens(query: string, screens: readonly HelpScreen[] = HELP_SCREENS): HelpScreen[] {
  const words = query.toLowerCase().split(/\s+/).filter((w) => w.length > 0);
  if (words.length === 0) return [...screens];
  return screens.filter((s) => {
    const hay = [s.id, s.title, s.module, s.route, s.capability, s.reads, s.live, s.status].join(' ').toLowerCase();
    return words.every((w) => hay.includes(w));
  });
}
